[versions]
aboutlibrariesCore = "11.2.3"
agp = "8.13.2"
coilCompose = "3.3.0"
composeBomVersion = "2026.01.00"
core = "6.0.0"
desugar_jdk_libs = "2.1.5"
editorBom = "0.24.4"
fragmentKtx = "1.8.9"
documentfile = "1.1.0"
gson = "2.13.2"
hiddenapibypass = "6.1"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
material3Version = "1.5.0-alpha12"
miuix = "0.7.2"
tinypinyin = "2.0.3.RELEASE"
navigationCompose = "2.9.6"
playServicesLocation = "21.3.0"
preference = "2.1.1"
runtimeAnnotation = "1.10.1"
shizukuVersion = "13.1.5"
foundationLayout = "1.10.1"
ui = "1.10.1"
room = "2.8.4"
appcompat = "1.7.1"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibrariesCore" }
androidx-compose-bom-v20251200 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3Version" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
api = { module = "dev.rikka.shizuku:api", version.ref = "shizukuVersion" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
core = { module = "com.github.topjohnwu.libsu:core", version.ref = "core" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
editor = { module = "io.github.rosemoe:editor" }
editor-bom = { module = "io.github.rosemoe:editor-bom", version.ref = "editorBom" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
miuix = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }
tinypinyin = { group = "io.github.biezhi", name = "TinyPinyin", version.ref = "tinypinyin" }
nio = { module = "com.github.topjohnwu.libsu:nio", version.ref = "core" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
preference = { module = "me.zhanghai.compose.preference:preference", version.ref = "preference" }
androidx-compose-runtime-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "runtimeAnnotation" }
provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizukuVersion" }
materialKolor = "com.materialkolor:material-kolor:4.1.0"
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
languageTextmate = { module = "io.github.rosemoe:language-textmate" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
service = { module = "com.github.topjohnwu.libsu:service", version.ref = "core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
